### ISSUE TITLE
Correcciones y sugerencias

### ISSUE THREAD

**Issue by PalumboN** [dimoulasLucas/macowins-implementacion-2021#1]
Hola @dimoulasLucas cómo estás? Te dejo algunos comentarios que fui anotando mientras miraba tu solución:

- Falta indicar el tipo de prenda (sacos, pantalones, camisas). Además cuando instanciemos una prenda vamos a querer indicar tanto el precio base como su estado, por lo tanto se debería recibir ambos en un mismo contructor, y no tener 2 formas de instanciar una prenda:
https://github.com/dimoulasLucas/macowins-implementacion-2021/blob/10873610154f2bd1cd45060eb153e4736a6633ff/src/main/java/macowins.java#L46-L58

- El enunciado cuenta que una venta tiene asociada las prendas con las cantidades _que se venden de cada una_. Según el modelo actual, en el caso de una venta de muchas prendas iguales, se deberán instanciar muchos objetos con características similares:
https://github.com/dimoulasLucas/macowins-implementacion-2021/blob/10873610154f2bd1cd45060eb153e4736a6633ff/src/main/java/macowins.java#L17-L20

- La venta con tarjeta acá quedó sin comportamiento, lo que es un _bad smell_, pero [acá](https://drive.google.com/file/d/1UHg0kZlcXmkSxMgV28gqUJ0myd8wZqYF/view) sí aparece y muy bien.

- Quedó pendiente el requerimiento para **saber saber las ganancias de un determinado día**. Si bien aparece un objeto para guardar las ventas que se hacen no está la lógica para saber la ganancia de un día. 
En [este modelo](https://drive.google.com/file/d/1UHg0kZlcXmkSxMgV28gqUJ0myd8wZqYF/view) entiendo que se quiere crear una clase día por cada día y acumular las ventas ahí pero falta especificar cómo sería esa lógica. Por otro lado, no hay necesidad de _precalcular_ los conjuntos de ventas por día, se podría calcular al momento de necesitarlo.
Y acá tenés un objeto `macowins` que tiene la responsabilidad de un _Repositorio_ (ya vamos a ver qué significa esto en la cursada)
https://github.com/dimoulasLucas/macowins-implementacion-2021/blob/10873610154f2bd1cd45060eb153e4736a6633ff/src/main/java/macowins.java#L7-L9

- El diagrama de clases está bien.

**Comment by dimoulasLucas** [comment]
Muchas gracias @PalumboN por las correcciones de mi ejercicio! Tendré en cuenta todas las correcciones hechas a la hora de implementar mi TP individual a entregar. Con estas correcciones, y agregando lo discutido en clase me quedó muy claro todo.

Te mando un saludo.
